# Generated by Django 3.2.5 on 2021-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('pending', 'pending'), ('completed', 'completed'), ('awaiting_payment', 'awaiting_payment'),
                         ('shipped', 'shipped'), ('cancelled', 'cancelled'), ('declined', 'declined')],
                default='pending', max_length=50),
        ),
    ]
