# Generated by Django 3.2.5 on 2021-08-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0007_auto_20210814_1528'),
        ('orders', '0004_auto_20210808_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_car',
                                    to='cars.car'),
        ),
    ]
