# Generated by Django 3.2.5 on 2021-08-05 09:03

from django.db import migrations, models
import django.db.models.deletion
from dealer.dealers.models import Country


def country_from_city_to_newtable(apps, schema_editor):
    City = apps.get_model('dealers', 'City')
    for city in City.objects.distinct('country'):
        Country.objects.create(name=city.country, code=str(city.country)[:2].lower())
    for city in City.objects.all():
        city.country = Country.objects.filter(name=city.country).first().id
        city.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва країни')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RunPython(country_from_city_to_newtable),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Дилер', 'verbose_name_plural': 'Дилери'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва міста'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.country',
                                    verbose_name='Назва країни'),
        ),
    ]
