# Generated by Django 3.2.5 on 2021-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dealers', '0002_auto_20210805_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Країна', 'verbose_name_plural': 'Країни'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва міста'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва країни'),
        ),
    ]
