# Generated by Django 3.2.5 on 2021-08-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dealers', '0003_auto_20210805_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
