# Generated by Django 3.2.5 on 2021-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_car',
            options={'verbose_name': 'Модель машини', 'verbose_name_plural': 'Моделі машин'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='populationtype',
        ),
        migrations.AddField(
            model_name='car',
            name='pollutant_class',
            field=models.CharField(
                choices=[('high_plus', 'A+'), ('high', 'A'), ('middle_high', 'B'), ('middle', 'C'), ('middle_low', 'D'),
                         ('low_high', 'E'), ('low', 'F'), ('very_low', 'G')], default='C', max_length=50),
        ),
    ]
