# Generated by Django 3.2.5 on 2021-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_auto_20210803_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearcase',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Used', 'used'), ('Forapart', 'for a part'),
                                            ('Hadbeencrashed', 'had been crashed')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='model_car',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
