# Generated by Django 3.2.5 on 2021-08-06 17:04

from django.db import migrations, models
import django.db.models.deletion
from dealer.cars.models import FuelType


def change_fueltype_in_cartable(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    for car in Car.objects.distinct('fueltype'):
        FuelType.objects.create(name=car.fueltype)
    for car in Car.objects.all():
        car.fueltype = FuelType.objects.filter(name=car.fueltype).first().id
        car.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0003_auto_20210806_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[('gas', 'gas'), ('disel', 'disel'), ('gasolin', 'gasolin'), ('electrical', 'electrical')],
                    default='disel', max_length=20)),
            ],
        ),
        migrations.RunPython(change_fueltype_in_cartable),
        migrations.AlterField(
            model_name='car',
            name='fueltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.fueltype'),
        ),
    ]
