# Generated by Django 3.2.5 on 2021-08-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dealers', '0004_dealer_email'),
        ('cars', '0005_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(
                choices=[('gas', 'gas'), ('disel', 'disel'), ('gasolin', 'gasolin'), ('electrical', 'electrical')],
                default='disel', max_length=20, unique=True),
        ),
    ]
