# Generated by Django 3.2.5 on 2021-08-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dealers', '0004_dealer_email'),
        ('cars', '0006_auto_20210808_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers_cars',
                                    to='dealers.dealer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model',
                                    to='cars.model_car'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture',
                                       to='cars.car'),
        ),
    ]
