# Generated by Django 3.2.5 on 2021-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_status_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
