# Generated by Django 3.2.5 on 2021-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_color_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
