# Generated by Django 3.2.5 on 2021-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210821_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='view_for_statistic',
            field=models.JSONField(default='{}'),
        ),
    ]
