# Generated by Django 3.2.5 on 2021-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_view_for_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='view_for_statistic',
            field=models.JSONField(blank=True, default='{"2021": {"2021-08-29": 0}}', null=True),
        ),
    ]
